name: bingbong2
description: A new Flutter application.

publish_to: 'none'

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  camera: ^0.9.4+19
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  flutter_screenutil: ^5.4.0
  scidart: ^0.0.2-dev.9
  get_it: ^7.2.0
  equatable: ^2.0.3


  #cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/models/
    - assets/images/
